name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake (light mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: cheongcode
          outputs: |
            dist/snake.svg
            dist/snake.gif?color_snake=b678c4&color_dots=#8871e5,#b678c4,#00d4ff

      - name: Generate snake (dark mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: cheongcode
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-dark.gif?color_snake=b678c4&color_dots=#8871e5,#b678c4,#00d4ff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
